### ISSUE TITLE
Treat HTTP 204 as error

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/zswag#115]
In the NDS.Live context, both 204, 404 and empty responses are used to indicate that a tile is not available. This currently leads to error messages for every unavailable tile. It should be possible to suppress these errors, and throw an `EmptyResponse` exception instead.

**Comment by fklebert** [comment]
After discussion we have figured out that:
- HTTP 200 with empty response is a valid return, as some zserio services may expect empty structs
- We need to treat every other response than HTTP 200 as error since zswag passes the body onto zserio to parse it. Zserio will throw an exception on any return value from the 200 range besides 200 and a parsable (or empty) zserio binary

Thus we can simplify the change to treat everything than HTTP 200 as error.
